# TASK 1 

In [3]:
num_list = [2, 5, 7, 8, 10, 3]

even_squares = []
odd_cubes = []

for n in num_list:
    if n % 2 == 0:
        even_squares.append(n**2)
    else:
        odd_cubes.append(n**3)

merged_list = sorted(even_squares + odd_cubes)

print("Even Squares:", even_squares)
print("Odd Cubes:", odd_cubes)
print("Merged Sorted:", merged_list)

Even Squares: [4, 64, 100]
Odd Cubes: [125, 343, 27]
Merged Sorted: [4, 27, 64, 100, 125, 343]


In [ ]:
# TASK 2

In [5]:
# Creating dictionary
entities = {}

entities[1] = {"name": "A", "category": "X", "value": 75}
entities[2] = {"name": "B", "category": "Y", "value": 40}
entities[3] = {"name": "C", "category": "X", "value": 90}
entities[4] = {"name": "D", "category": "Z", "value": 60}
entities[5] = {"name": "E", "category": "Y", "value": 30}

values = {k: v["value"] for k, v in entities.items()}

max_entity = max(values, key=values.get)
print("Maximum:", entities[max_ent])

min_entity = min(values, key=values.get)
print("Minimum:", entities[min_ent])

sorted_entities = sorted(entities.items(), key=lambda x: x[1]["value"])

print("Sorted Entities:")
for k,v in sorted_entities:
    print(v)


Maximum: {'name': 'C', 'category': 'X', 'value': 90}
Minimum: {'name': 'E', 'category': 'Y', 'value': 30}
Sorted Entities:
{'name': 'E', 'category': 'Y', 'value': 30}
{'name': 'B', 'category': 'Y', 'value': 40}
{'name': 'D', 'category': 'Z', 'value': 60}
{'name': 'A', 'category': 'X', 'value': 75}
{'name': 'C', 'category': 'X', 'value': 90}


In [ ]:
#TASK 3 

In [8]:
numbers = [10, 50, 100, 80, 30]

abs_difference = lambda a,b: abs(a-b)

min_value = min(numbers)
max_value = max(numbers)

normalize = lambda x: (x-min_value)/(max_value-min_value)

normalized = list(map(normalize, numbers))
filtered = list(filter(lambda x: x>0.5, normalized))

print("Normalized:", normalized)
print("Filtered (>0.5):", filtered)
print("Absolute Difference:", abs_difference(10,50))


Normalized: [0.0, 0.4444444444444444, 1.0, 0.7777777777777778, 0.2222222222222222]
Filtered (>0.5): [1.0, 0.7777777777777778]
Absolute Difference: 40


In [ ]:
#TASK 4

In [12]:
import numpy as np

matrix = np.random.rand(6,4)

print(matrix)
print("Shape:", matrix.shape)
print("Size:", matrix.size)
print("Type:", matrix.dtype)

print("Column Mean:", np.mean(matrix,axis=0))
print("Row Max:", np.max(matrix,axis=1))
print("Index of Max:", np.argmax(matrix))



[[0.05532873 0.14402423 0.09090323 0.27645921]
 [0.82770572 0.89948072 0.75011754 0.53609205]
 [0.97026557 0.06728376 0.15792794 0.45456741]
 [0.51439019 0.28747509 0.04983845 0.78139281]
 [0.46102544 0.81148045 0.73185284 0.08735214]
 [0.74724564 0.68896763 0.45534053 0.0906491 ]]
Shape: (6, 4)
Size: 24
Type: float64
Column Mean: [0.59599355 0.48311865 0.37266342 0.37108545]
Row Max: [0.27645921 0.89948072 0.97026557 0.78139281 0.81148045 0.74724564]
Index of Max: 8


In [ ]:
#TASK 5

In [13]:
import numpy as np
scores_array = np.array([
    [80, 70, 90],
    [60, 75, 65],
    [85, 88, 92],
    [70, 60, 75]
])

average_scores = np.mean(scores_array, axis=1)
print("Average Scores:", average_scores)

ranking = np.argsort(average_scores)[::-1]
print("System Ranking (Best to Worst):", ranking)

print("\nSystems from Best to Worst:")
for i in ranking:
    print("System", i, "Average Score:", average_scores[i])

Average Scores: [80.         66.66666667 88.33333333 68.33333333]
System Ranking (Best to Worst): [2 0 3 1]

Systems from Best to Worst:
System 2 Average Score: 88.33333333333333
System 0 Average Score: 80.0
System 3 Average Score: 68.33333333333333
System 1 Average Score: 66.66666666666667


In [ ]:
#TASK 6

In [20]:
import numpy as np

data = np.random.rand(100,3)

normalization = (data - np.min(data,axis=0)) / (np.max(data,axis=0)-np.min(data,axis=0))

stds = np.std(normalization,axis=0)
highest_std_column = np.argmax(stds)

row_sum = np.sum(norm,axis=1)
row_max = np.argmax(row_sum)

print("Column with highest variation:", highest_std_column)
print("Row with maximum total:", row_max)

Column with highest variation: 2
Row with maximum total: 38


In [ ]:
#TASK 7

In [16]:
area = [112.0,113.5,189.5,789.0,230.2,"20.0"]

float_area = area[:]
float_area = [x for x in float_area if type(x)==float]
str_area = [x for x in area if type(x)==str]

print("All:", area[:])
print("Float:", float_area[:])
print("Str:", str_area[:])

print("Bedroom Area:", area[0:2])

All: [112.0, 113.5, 189.5, 789.0, 230.2, '20.0']
Float: [112.0, 113.5, 189.5, 789.0, 230.2]
Str: ['20.0']
Bedroom Area: [112.0, 113.5]


In [ ]:
#TASK 8

In [17]:
def flatten(list):
    result_array=[]
    for i in list:
        if type(i)==list:
            result_array.extend(flatten(i))
        else:
            result_array.append(i)
    return result_array

house_extensions = ['bed',112.0,'hall',113.5,'bath',189.5,'kit',789.0,'liv',230.0,
         ['pool',112.7,117.9],['grg',112.0]]

print(flatten(house_extensions))

['bed', 112.0, 'hall', 113.5, 'bath', 189.5, 'kit', 789.0, 'liv', 230.0, ['pool', 112.7, 117.9], ['grg', 112.0]]


In [ ]:
#TASK 9

In [19]:
students = [
{'student_id':1,'name':'Jean Castro','class':'V'},
{'student_id':2,'name':'Lula Powell','class':'V'},
{'student_id':3,'name':'Brian Howell','class':'VI'}
]

all_values = [list(d.values()) for d in students]
id_name = [[d['student_id'],d['name']] for d in students]
name_class = [[d['name'],d['class']] for d in students]

print(all_values)
print(id_name)
print(name_class)


[[1, 'Jean Castro', 'V'], [2, 'Lula Powell', 'V'], [3, 'Brian Howell', 'VI']]
[[1, 'Jean Castro'], [2, 'Lula Powell'], [3, 'Brian Howell']]
[['Jean Castro', 'V'], ['Lula Powell', 'V'], ['Brian Howell', 'VI']]


In [ ]:
#TASK 10

In [21]:
Fav_food_items = [
 ['pizza','burger','hotdogs'],
 ['pasta','hotdogs'],
 ['pizza'],
 ['burger','hotdogs'],
 ['rice','pasta'],
 ['pasta']
]

def is_subset(a,b):
    for item in a:
        if item not in b:
            return False
    return True

result_array=[]

for i in range(len(Fav_food_items)):
    subset=False
    for j in range(len(Fav_food_items)):
        if i!=j and is_subset(Fav_food_items[i],Fav_food_items[j]):
            subset=True
    if not subset:
        result_array.append(i)

print(result_array)

[0, 1, 4]


In [ ]:
#TASK 11 

In [23]:
activities = ['login','logout','login','purchase','login','purchase','logout','login']

frequency_count = {}
for a in activities:
    frequency_count[a]=frequency_count.get(a,0)+1

sorted_frequencies = sorted(frequency_count.items(),key=lambda x:x[1],reverse=True)

print("Frequency:",frequency_count)
print("Sorted Frequencies:",sorted_frequencies)
print("Most frequent activity:",sorted_frequencies[0])
print("Least frequent activity:",sorted_frequencies[-1])


Frequency: {'login': 4, 'logout': 2, 'purchase': 2}
Sorted Frequencies: [('login', 4), ('logout', 2), ('purchase', 2)]
Most frequent activity: ('login', 4)
Least frequent activity: ('purchase', 2)


In [ ]:
#TASK 12 

In [25]:
resource_usage = [
{'cpu':45,'memory':70},
{'cpu':85,'memory':90},
{'cpu':60,'memory':40},
{'cpu':95,'memory':88},
{'cpu':30,'memory':20}
]

valid=[u for u in resource_usage if u['cpu']>80 and u['memory']>75]

cpu_values=[u['cpu'] for u in resource_usage]
memory_values=[u['memory'] for u in resource_usage]

normalized=lambda x,minv,maxv:(x-minv)/(maxv-minv)

scores_array=[]
for u in resource_usage:
    c=normalized(u['cpu'],min(cpu_values),max(cpu_values))
    m=normalized(u['memory'],min(memory_values),max(memory_values))
    scores_array.append(c+m)

rank=np.argsort(scores_array)[::-1]

print("Valid:",valid)
print("Ranking:",rank)


Valid: [{'cpu': 85, 'memory': 90}, {'cpu': 95, 'memory': 88}]
Ranking: [3 1 0 2 4]


In [ ]:
#TASK 13 

In [26]:
students=[
{'student_id':1,'name':'Jean Castro','class':'V'},
{'student_id':2,'name':'Lula Powell','class':'V'},
{'student_id':3,'name':'Brian Howell','class':'VI'},
{'student_id':4,'name':'Lynne Foster','class':'VI'},
{'student_id':5,'name':'Zachary Simon','class':'VII'}
]

all_values=[list(s.values()) for s in students]
id_name=[[s['student_id'],s['name']] for s in students]
name_class=[[s['name'],s['class']] for s in students]

print(all_values)
print(id_name)
print(name_class)


[[1, 'Jean Castro', 'V'], [2, 'Lula Powell', 'V'], [3, 'Brian Howell', 'VI'], [4, 'Lynne Foster', 'VI'], [5, 'Zachary Simon', 'VII']]
[[1, 'Jean Castro'], [2, 'Lula Powell'], [3, 'Brian Howell'], [4, 'Lynne Foster'], [5, 'Zachary Simon']]
[['Jean Castro', 'V'], ['Lula Powell', 'V'], ['Brian Howell', 'VI'], ['Lynne Foster', 'VI'], ['Zachary Simon', 'VII']]


In [ ]:
#TASK 14

In [27]:
import random

var = tuple(random.randint(1,50) for i in range(10))
lst=list(var)

for i in range(len(lst)):
    for j in range(i+1,len(lst)):
        if lst[i]>lst[j]:
            lst[i],lst[j]=lst[j],lst[i]

sorted_tuple=tuple(lst)
print(var)
print(sorted_tuple)


(21, 5, 29, 31, 30, 31, 17, 19, 23, 4)
(4, 5, 17, 19, 21, 23, 29, 30, 31, 31)


In [ ]:
#TASK 15

In [28]:
import numpy as np

array=np.random.rand(3,5,4)
swapped=array[:,::-1,::-1]

print(array.shape)
print(swapped.shape)


(3, 5, 4)
(3, 5, 4)
